version: '3.7'

services:
  app:
    build: .
    command: ["./entrypoint.sh", "flask", "run", "--host=0.0.0.0", "--port=8000"]
    ports:
      - "8000:8000"
    environment:
      FLASK_APP: app.main
      DATABASE_URL: postgresql://fiap:fiap@db:5432/videoproject
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - my_shared_network
    volumes:
      - .:/app

  db:
    image: postgres:15.3
    environment:
      POSTGRES_USER: fiap
      POSTGRES_PASSWORD: fiap
      POSTGRES_DB: videoproject
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_shared_network

  redis:
    image: redis:7.2.1
    ports:
      - "6379:6379"
    networks:
      - my_shared_network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery worker --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - .:/app
    networks:
      - my_shared_network

volumes:
  postgres_data:

networks:
  my_shared_network:
    external: false 
