apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: video-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: video-processor
  template:
    metadata:
      labels:
        app: video-processor
    spec:
      containers:
      - name: video-processor-app
        image: your-docker-image:latest
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: "redis-service"
