apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: deboraferrarids2/worker:latest
        command: ["celery", "-A", "app.celery_utils", "worker", "--loglevel=info"]
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: CELERY_RESULT_BACKEND
          value: "redis://redis-service:6379/0"
