"""Automated migration

Revision ID: 1bb6c3bafbd7
Revises: 30e810da3a5e
Create Date: 2025-01-20 20:04:41.459052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb6c3bafbd7'
down_revision = '30e810da3a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_video_name', sa.String(length=255), nullable=False),
    sa.Column('zip_file_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_videos')
    # ### end Alembic commands ###
